name: PR Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/pr-build.yaml@v10.1
    with:
      solution: "SharpMud.slnx"
      hasTests: true
      useMtpRunner: true
      runCdk: false
      dotnetVersion: "11.0.x"
